"use client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import { toast } from "sonner";
import { addNewCompanyStats } from "@/services/admin-services";
import { ChevronLeft } from "lucide-react";
import { useRouter } from "next/navigation";

// Validation Schema
const schema = yup.object({
  company: yup.string().required("Company name is required"),
  email: yup.string().email("Must be a valid email").required("Email is required"),
});

interface FormData {
  company: string;
  email: string;
  firstName?: string; // Optional field
  lastName?: string; // Optional field
}

const Page = () => {
  const [backendError, setBackendError] = useState<string | null>(null); // State for backend errors
  const router = useRouter();

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<FormData>({
    resolver: yupResolver(schema),
    defaultValues: {
      company: "",
      email: "",
      firstName: "", // Optional field
      lastName: "", // Optional field
    },
  });

  // Function to generate a random 6-digit password
  const generateRandomPassword = (): string => {
    return Math.floor(100000 + Math.random() * 900000).toString(); // Generates a 6-digit number
  };

  const onSubmit = async (data: FormData) => {
    try {
      setBackendError(null); // Clear previous backend errors before submitting

      const autoGeneratedPassword = generateRandomPassword();
      const payload = {
        companyName: data.company,
        email: data.email,
        password: autoGeneratedPassword, // Auto-generated 6-digit password
        firstName: data.firstName || "", // Optional field, default to empty string
        lastName: data.lastName || "", // Optional field, default to empty string
      };

      const response = await addNewCompanyStats("/admin/create-company", payload);

      if (response?.status === 201 || response?.status === 200) {
        toast.success("Company added successfully", {
        duration: Infinity,
        position: "top-center",
        action: {
          label: "OK",
          onClick: (toastId : any) => toast.dismiss(toastId),
        },
        closeButton: false,
      });
        reset(); // Reset the form after successful submission
        window.location.href = "/admin/company-lists";
      } else {
        const errorMessage = response?.data?.message || "Failed to add company";
        setBackendError(errorMessage); // Set backend error
        toast.error(errorMessage, {
                duration: Infinity,
                position: "top-center",
                action: {
                  label: "OK",
                  onClick: (toastId : any) => toast.dismiss(toastId),
                },
                closeButton: false,
              });
      }
    } catch (error: any) {
      console.error("Error adding company:", error);
      const errorMessage =
        error.response?.data?.message || "An error occurred while adding the company";
      setBackendError(errorMessage); // Set backend error from catch block
      toast.error(errorMessage, {
              duration: Infinity,
              position: "top-center",
              action: {
                label: "OK",
                onClick: (toastId : any) => toast.dismiss(toastId),
              },
              closeButton: false,
            });
    }
  };

  return (
    <div className="grid grid-cols-12 gap-4 h-screen w-full">
      <div className="col-span-12 space-y-6 bg-[#1b2236] rounded-[12px] md:rounded-[20px] py-4 px-4 md:py-8 md:px-9">
        <div className="flex items-center gap-2 mb-4">
          <Button
            variant="destructive"
            className="bg-[#0B132B] hover:bg-[#0B132B] p-0 h-7 w-7 hover:cursor-pointer"
            onClick={() => router.back()}
          >
            <ChevronLeft />
          </Button>
          <h2 className="text-white text-[20px] md:text-2xl font-bold">Add New Company</h2>
        </div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label htmlFor="company" className="text-white dm-sans text-base font-normal">
                Company Name
              </Label>
              <Input
                id="company"
                type="text"
                {...register("company")}
                className="bg-[#0f172a] h-12 border-none text-white"
              />
              {errors.company && (
                <p className="text-red-500 text-sm">{errors.company.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="email" className="text-white dm-sans text-base font-normal">
                Email Address
              </Label>
              <Input
                id="email"
                type="text"
                {...register("email")}
                className="bg-[#0f172a] h-12 border-none text-white"
              />
              {errors.email && (
                <p className="text-red-500 text-sm">{errors.email.message}</p>
              )}
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label htmlFor="firstName" className="text-white dm-sans text-base font-normal">
                First Name
              </Label>
              <Input
                id="firstName"
                type="text"
                {...register("firstName")}
                className="bg-[#0f172a] h-12 border-none text-white"
              />
              {errors.firstName && (
                <p className="text-red-500 text-sm">{errors.firstName.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="lastName" className="text-white dm-sans text-base font-normal">
                Last Name
              </Label>
              <Input
                id="lastName"
                type="text"
                {...register("lastName")}
                className="bg-[#0f172a] h-12 border-none text-white"
              />
              {errors.lastName && (
                <p className="text-red-500 text-sm">{errors.lastName.message}</p>
              )}
            </div>
          </div>

          {/* Display backend error */}
          {backendError && (
            <p className="text-red-500 text-sm mt-4">{backendError}</p>
          )}

          <div>
            <Button
              type="submit"
              className="mt-6 bg-[#1A3F70] w-64 h-11 cursor-pointer hover:bg-[#1A3F70] dm-sans text-white"
              disabled={isSubmitting}
            >
              {isSubmitting ? "Saving..." : "Save"}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Page;